[build]
  command = "npm run build:meta"
  publish = "."

[[redirects]]
  from = "/admin"
  to = "/admin/"
  status = 301

[[redirects]]
  from = "/callback"
  to = "/.netlify/functions/auth"
  status = 200
